# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
   # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Build image BE in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd ../../ &&
            cd home/node36/node36_sequelize &&
            git checkout main &&
            git pull origin main &&
            sudo docker images -af reference='node36' -q &&
            sudo docker build . -t node36
          '

      - name: Build container in EC2
        env:
            PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USER  }}
            
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
            cd ../../ &&
            cd home/node36/node36_sequelize &&
            sudo docker ps -q --filter "name=cons-node36" | grep -q . && sudo docker rm -f cons-node36 &&
            sudo docker run -d -p 8080:8080 --name cons-node36 node36
          '
